package tcc;

import javax.swing.*;  
import java.awt.*;
import java.sql.*; 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Higor
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        conf_email_PF_CAD = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        tratamento_PF_CAD = new javax.swing.JComboBox();
        nome_PF_CAD = new javax.swing.JTextField();
        estado_PF_CAD = new javax.swing.JComboBox();
        CEP = new javax.swing.JLabel();
        email_PF_CAD = new javax.swing.JTextField();
        Cidade = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        rua_PF_CAD = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        numero_PF_CAD = new javax.swing.JSpinner();
        conf_Email = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        bairro_PF_CAD = new javax.swing.JTextField();
        conf_Senha = new javax.swing.JLabel();
        cidade_PF_CAD = new javax.swing.JTextField();
        conf_senha_PF_CAD = new javax.swing.JTextField();
        senha_PF_CAD = new javax.swing.JTextField();
        cep_PF_CAD = new javax.swing.JFormattedTextField();
        Bairro = new javax.swing.JLabel();
        Rua = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        cpf_PF_CAD = new javax.swing.JFormattedTextField();
        rg_PF_CAD = new javax.swing.JFormattedTextField();
        telefone_2_PF_CAD = new javax.swing.JFormattedTextField();
        celular_PF_CAD = new javax.swing.JFormattedTextField();
        Telefone_2 = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Telefone_1 = new javax.swing.JLabel();
        telefone_1_PF_CAD = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        dia_nascimento_PF_CAD = new javax.swing.JComboBox();
        mes_nascimento_PF_CAD = new javax.swing.JComboBox();
        ano_nascimento_PF_CAD = new javax.swing.JComboBox();
        limpar_PF_CAD = new javax.swing.JButton();
        cadastrar_PF_CAD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_PF_CAD = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        sair_PF_CAD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cadastrar_PJ_CAD = new javax.swing.JButton();
        limpar_PJ_CAD = new javax.swing.JButton();
        sair_PJ_CAD = new javax.swing.JButton();
        conf_senha_PJ_CAD = new javax.swing.JTextField();
        senha_PJ_CAD = new javax.swing.JTextField();
        conf_email_PJ_CAD = new javax.swing.JTextField();
        email_PJ_CAD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto_PJ_CAD = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cidade_PJ_CAD = new javax.swing.JTextField();
        numero_PJ_CAD = new javax.swing.JSpinner();
        rua_PJ_CAD = new javax.swing.JTextField();
        estado_PJ_CAD = new javax.swing.JComboBox();
        cpf_PJ_CAD = new javax.swing.JFormattedTextField();
        nome_PJ_CAD = new javax.swing.JTextField();
        Nome1 = new javax.swing.JLabel();
        RG1 = new javax.swing.JLabel();
        Telefone_3 = new javax.swing.JLabel();
        CEP1 = new javax.swing.JLabel();
        Rua1 = new javax.swing.JLabel();
        Bairro1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        conf_Email1 = new javax.swing.JLabel();
        Senha1 = new javax.swing.JLabel();
        conf_Senha1 = new javax.swing.JLabel();
        bairro_PJ_CAD = new javax.swing.JTextField();
        cep_PJ_CAD = new javax.swing.JFormattedTextField();
        Telefone_4 = new javax.swing.JLabel();
        telefone_2_PJ_CAD = new javax.swing.JFormattedTextField();
        CPF1 = new javax.swing.JLabel();
        cnpj_PJ_CAD = new javax.swing.JFormattedTextField();
        telefone_1_PJ_CAD = new javax.swing.JFormattedTextField();
        Estado1 = new javax.swing.JLabel();
        Cidade1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tratamento_PJ_CAD = new javax.swing.JComboBox();
        Telefone_5 = new javax.swing.JLabel();
        telefone_3_PJ_CAD = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane2.setName(""); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tcc/Bundle"); // NOI18N
        conf_email_PF_CAD.setText(bundle.getString("Cadastrar.conf_email_PF_CAD.text")); // NOI18N

        Estado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Estado.setText(bundle.getString("Cadastrar.Estado.text")); // NOI18N

        tratamento_PF_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Sr.", "Sra." }));
        tratamento_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamento_PF_CADActionPerformed(evt);
            }
        });

        nome_PF_CAD.setText(bundle.getString("Cadastrar.nome_PF_CAD.text")); // NOI18N
        nome_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_PF_CADActionPerformed(evt);
            }
        });

        estado_PF_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        CEP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CEP.setText(bundle.getString("Cadastrar.CEP.text")); // NOI18N

        email_PF_CAD.setText(bundle.getString("Cadastrar.email_PF_CAD.text")); // NOI18N

        Cidade.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cidade.setText(bundle.getString("Cadastrar.Cidade.text")); // NOI18N

        Nome.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Nome.setText(bundle.getString("Cadastrar.Nome.text")); // NOI18N

        rua_PF_CAD.setText(bundle.getString("Cadastrar.rua_PF_CAD.text")); // NOI18N

        Email.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Email.setText(bundle.getString("Cadastrar.Email.text")); // NOI18N

        conf_Email.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        conf_Email.setText(bundle.getString("Cadastrar.conf_Email.text")); // NOI18N

        Senha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Senha.setText(bundle.getString("Cadastrar.Senha.text")); // NOI18N

        bairro_PF_CAD.setText(bundle.getString("Cadastrar.bairro_PF_CAD.text")); // NOI18N

        conf_Senha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        conf_Senha.setText(bundle.getString("Cadastrar.conf_Senha.text")); // NOI18N

        cidade_PF_CAD.setText(bundle.getString("Cadastrar.cidade_PF_CAD.text")); // NOI18N

        conf_senha_PF_CAD.setText(bundle.getString("Cadastrar.conf_senha_PF_CAD.text")); // NOI18N

        senha_PF_CAD.setText(bundle.getString("Cadastrar.senha_PF_CAD.text")); // NOI18N

        cep_PF_CAD.setText(bundle.getString("Cadastrar.cep_PF_CAD.text")); // NOI18N
        cep_PF_CAD.setInheritsPopupMenu(true);
        cep_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_PF_CADActionPerformed(evt);
            }
        });

        Bairro.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Bairro.setText(bundle.getString("Cadastrar.Bairro.text")); // NOI18N

        Rua.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Rua.setText(bundle.getString("Cadastrar.Rua.text")); // NOI18N

        RG.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RG.setText(bundle.getString("Cadastrar.RG.text")); // NOI18N

        CPF.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CPF.setText(bundle.getString("Cadastrar.CPF.text")); // NOI18N

        cpf_PF_CAD.setText(bundle.getString("Cadastrar.cpf_PF_CAD.text")); // NOI18N
        cpf_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_PF_CADActionPerformed(evt);
            }
        });

        rg_PF_CAD.setText(bundle.getString("Cadastrar.rg_PF_CAD.text")); // NOI18N

        telefone_2_PF_CAD.setText(bundle.getString("Cadastrar.telefone_2_PF_CAD.text")); // NOI18N

        celular_PF_CAD.setText(bundle.getString("Cadastrar.celular_PF_CAD.text")); // NOI18N
        celular_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celular_PF_CADActionPerformed(evt);
            }
        });

        Telefone_2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telefone_2.setText(bundle.getString("Cadastrar.Telefone_2.text")); // NOI18N

        Celular.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Celular.setText(bundle.getString("Cadastrar.Celular.text")); // NOI18N

        Telefone_1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telefone_1.setText(bundle.getString("Cadastrar.Telefone_1.text")); // NOI18N

        telefone_1_PF_CAD.setText(bundle.getString("Cadastrar.telefone_1_PF_CAD.text")); // NOI18N
        telefone_1_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_1_PF_CADActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText(bundle.getString("Cadastrar.jLabel1.text")); // NOI18N

        dia_nascimento_PF_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dia", "1", "2", "3", "4", "5", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_nascimento_PF_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ano_nascimento_PF_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ano", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));

        limpar_PF_CAD.setBackground(new java.awt.Color(255, 255, 255));
        limpar_PF_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        limpar_PF_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        limpar_PF_CAD.setText(bundle.getString("Cadastrar.limpar_PF_CAD.text")); // NOI18N
        limpar_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_PF_CADActionPerformed(evt);
            }
        });

        cadastrar_PF_CAD.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar_PF_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cadastrar_PF_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        cadastrar_PF_CAD.setText(bundle.getString("Cadastrar.cadastrar_PF_CAD.text")); // NOI18N
        cadastrar_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_PF_CADActionPerformed(evt);
            }
        });

        campo_PF_CAD.setColumns(20);
        campo_PF_CAD.setRows(5);
        jScrollPane1.setViewportView(campo_PF_CAD);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText(bundle.getString("Cadastrar.jLabel2.text")); // NOI18N

        sair_PF_CAD.setBackground(new java.awt.Color(255, 255, 255));
        sair_PF_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sair_PF_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        sair_PF_CAD.setText(bundle.getString("Cadastrar.sair_PF_CAD.text")); // NOI18N
        sair_PF_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_PF_CADActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel6.setText(bundle.getString("Cadastrar.jLabel6.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Kalinga", 1, 28)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jLabel8.setText(bundle.getString("Cadastrar.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(sair_PF_CAD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar_PF_CAD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar_PF_CAD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(conf_Email)
                            .addComponent(CEP)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Telefone_1)
                                    .addComponent(Nome)
                                    .addComponent(RG)
                                    .addComponent(jLabel1))
                                .addComponent(Rua, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Bairro, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Senha)
                            .addComponent(conf_Senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rg_PF_CAD)
                                .addGap(36, 36, 36)
                                .addComponent(CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpf_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(telefone_1_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Telefone_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefone_2_PF_CAD)
                                .addGap(65, 65, 65)
                                .addComponent(Celular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celular_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cep_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estado_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rua_PF_CAD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dia_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mes_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ano_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bairro_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conf_email_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senha_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conf_senha_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cidade_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tratamento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome_PF_CAD)))))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tratamento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RG)
                    .addComponent(CPF)
                    .addComponent(cpf_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rg_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celular_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Celular)
                    .addComponent(telefone_1_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone_1)
                    .addComponent(Telefone_2)
                    .addComponent(telefone_2_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano_nascimento_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Estado)
                        .addComponent(estado_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cep_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CEP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Rua))
                    .addComponent(numero_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rua_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cidade)
                    .addComponent(bairro_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conf_Email)
                            .addComponent(conf_email_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conf_senha_PF_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conf_Senha)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair_PF_CAD)
                    .addComponent(limpar_PF_CAD)
                    .addComponent(cadastrar_PF_CAD))
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        cadastrar_PF_CAD.getAccessibleContext().setAccessibleParent(this);

        jTabbedPane2.addTab(bundle.getString("Cadastrar.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        cadastrar_PJ_CAD.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar_PJ_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cadastrar_PJ_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        cadastrar_PJ_CAD.setText(bundle.getString("Cadastrar.cadastrar_PJ_CAD.text")); // NOI18N
        cadastrar_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_PJ_CADActionPerformed(evt);
            }
        });

        limpar_PJ_CAD.setBackground(new java.awt.Color(255, 255, 255));
        limpar_PJ_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        limpar_PJ_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        limpar_PJ_CAD.setText(bundle.getString("Cadastrar.limpar_PJ_CAD.text")); // NOI18N
        limpar_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_PJ_CADActionPerformed(evt);
            }
        });

        sair_PJ_CAD.setBackground(new java.awt.Color(255, 255, 255));
        sair_PJ_CAD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sair_PJ_CAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        sair_PJ_CAD.setText(bundle.getString("Cadastrar.sair_PJ_CAD.text")); // NOI18N
        sair_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_PJ_CADActionPerformed(evt);
            }
        });

        conf_senha_PJ_CAD.setText(bundle.getString("Cadastrar.conf_senha_PJ_CAD.text")); // NOI18N

        senha_PJ_CAD.setText(bundle.getString("Cadastrar.senha_PJ_CAD.text")); // NOI18N

        conf_email_PJ_CAD.setText(bundle.getString("Cadastrar.conf_email_PJ_CAD.text")); // NOI18N

        email_PJ_CAD.setText(bundle.getString("Cadastrar.email_PJ_CAD.text")); // NOI18N

        texto_PJ_CAD.setColumns(20);
        texto_PJ_CAD.setRows(5);
        jScrollPane2.setViewportView(texto_PJ_CAD);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText(bundle.getString("Cadastrar.jLabel3.text")); // NOI18N

        cidade_PJ_CAD.setText(bundle.getString("Cadastrar.cidade_PJ_CAD.text")); // NOI18N

        rua_PJ_CAD.setText(bundle.getString("Cadastrar.rua_PJ_CAD.text")); // NOI18N

        estado_PJ_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        cpf_PJ_CAD.setText(bundle.getString("Cadastrar.cpf_PJ_CAD.text")); // NOI18N
        cpf_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_PJ_CADActionPerformed(evt);
            }
        });

        nome_PJ_CAD.setText(bundle.getString("Cadastrar.nome_PJ_CAD.text")); // NOI18N
        nome_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_PJ_CADActionPerformed(evt);
            }
        });

        Nome1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Nome1.setText(bundle.getString("Cadastrar.Nome1.text")); // NOI18N

        RG1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RG1.setText(bundle.getString("Cadastrar.RG1.text")); // NOI18N

        Telefone_3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telefone_3.setText(bundle.getString("Cadastrar.Telefone_3.text")); // NOI18N

        CEP1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CEP1.setText(bundle.getString("Cadastrar.CEP1.text")); // NOI18N

        Rua1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Rua1.setText(bundle.getString("Cadastrar.Rua1.text")); // NOI18N

        Bairro1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Bairro1.setText(bundle.getString("Cadastrar.Bairro1.text")); // NOI18N

        Email1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Email1.setText(bundle.getString("Cadastrar.Email1.text")); // NOI18N

        conf_Email1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        conf_Email1.setText(bundle.getString("Cadastrar.conf_Email1.text")); // NOI18N

        Senha1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Senha1.setText(bundle.getString("Cadastrar.Senha1.text")); // NOI18N

        conf_Senha1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        conf_Senha1.setText(bundle.getString("Cadastrar.conf_Senha1.text")); // NOI18N

        bairro_PJ_CAD.setText(bundle.getString("Cadastrar.bairro_PJ_CAD.text")); // NOI18N

        cep_PJ_CAD.setText(bundle.getString("Cadastrar.cep_PJ_CAD.text")); // NOI18N
        cep_PJ_CAD.setInheritsPopupMenu(true);
        cep_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_PJ_CADActionPerformed(evt);
            }
        });

        Telefone_4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telefone_4.setText(bundle.getString("Cadastrar.Telefone_4.text")); // NOI18N

        telefone_2_PJ_CAD.setText(bundle.getString("Cadastrar.telefone_2_PJ_CAD.text")); // NOI18N

        CPF1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CPF1.setText(bundle.getString("Cadastrar.CPF1.text")); // NOI18N

        cnpj_PJ_CAD.setText(bundle.getString("Cadastrar.cnpj_PJ_CAD.text")); // NOI18N

        telefone_1_PJ_CAD.setText(bundle.getString("Cadastrar.telefone_1_PJ_CAD.text")); // NOI18N
        telefone_1_PJ_CAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_1_PJ_CADActionPerformed(evt);
            }
        });

        Estado1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Estado1.setText(bundle.getString("Cadastrar.Estado1.text")); // NOI18N

        Cidade1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cidade1.setText(bundle.getString("Cadastrar.Cidade1.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel7.setText(bundle.getString("Cadastrar.jLabel7.text")); // NOI18N

        tratamento_PJ_CAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "ESTATAL", "ME", "LTDA", "S.A.", " " }));

        Telefone_5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telefone_5.setText(bundle.getString("Cadastrar.Telefone_5.text")); // NOI18N

        telefone_3_PJ_CAD.setText(bundle.getString("Cadastrar.telefone_3_PJ_CAD.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Kalinga", 1, 28)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/empresa.png"))); // NOI18N
        jLabel5.setText(bundle.getString("Cadastrar.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CEP1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Telefone_3)
                            .addComponent(Nome1)
                            .addComponent(RG1))
                        .addComponent(Rua1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Bairro1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Email1)
                    .addComponent(conf_Email1)
                    .addComponent(Senha1)
                    .addComponent(conf_Senha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(conf_email_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senha_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conf_senha_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(telefone_1_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Telefone_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone_2_PJ_CAD)
                        .addGap(18, 18, 18)
                        .addComponent(Telefone_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone_3_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rua_PJ_CAD)
                        .addGap(18, 18, 18)
                        .addComponent(numero_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cep_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(278, 278, 278)
                            .addComponent(Estado1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(estado_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(nome_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tratamento_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cnpj_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CPF1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cpf_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bairro_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidade_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(email_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sair_PJ_CAD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpar_PJ_CAD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar_PJ_CAD)
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome1)
                    .addComponent(tratamento_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPF1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RG1)
                        .addComponent(cnpj_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cpf_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone_1_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone_3)
                    .addComponent(Telefone_4)
                    .addComponent(telefone_2_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone_5)
                    .addComponent(telefone_3_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEP1)
                    .addComponent(Estado1)
                    .addComponent(estado_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rua1)
                    .addComponent(numero_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bairro1)
                    .addComponent(bairro_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cidade1)
                    .addComponent(cidade_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email1)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conf_email_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conf_Email1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Senha1)
                            .addComponent(senha_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conf_senha_PJ_CAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conf_Senha1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair_PJ_CAD)
                    .addComponent(limpar_PJ_CAD)
                    .addComponent(cadastrar_PJ_CAD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(bundle.getString("Cadastrar.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_PF_CADActionPerformed
if(tratamento_PF_CAD.getSelectedItem().equals("---")){
tratamento_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "O campo de tratamento é obrigatório !","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(nome_PF_CAD.getText().equals("")){
nome_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "O campo 'NOME' é obrigatório !","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(rg_PF_CAD.getText().equals("")){
rg_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "O campo 'RG' é obrigatório","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(cpf_PF_CAD.getText().equals("")){
cpf_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "O campo 'CPF' é obrigatório","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(telefone_1_PF_CAD.getText().equals("")){
telefone_1_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Preencha ao menos um telefone","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(dia_nascimento_PF_CAD.getSelectedItem().equals("dia")){
dia_nascimento_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Em que dia você nasceu ?","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(mes_nascimento_PF_CAD.getSelectedItem().equals("mês")){
mes_nascimento_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Em que mês você nasceu ?","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(ano_nascimento_PF_CAD.getSelectedItem().equals("ano")){
ano_nascimento_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Em que ano você nasceu ?","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(cep_PF_CAD.getText().equals("")){
cep_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Pra ficar mais fácil, digite seu CEP que iremos preencher o restante","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(numero_PF_CAD.getValue().equals("0")){
numero_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "qual o numero da sua residência?","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(email_PF_CAD.getText().equals("")){
email_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "digite seu e-mail","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(conf_email_PF_CAD.getText().equals("")){
conf_email_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "repita seu e-mail","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

if(senha_PF_CAD.getText().equals("")){
senha_PF_CAD.requestFocus();
JOptionPane.showMessageDialog(null, "Pense em uma senha que não seja 123","aviso",JOptionPane.WARNING_MESSAGE );
return;
}

                if(conf_senha_PF_CAD.getText().equals("")){
                conf_senha_PF_CAD.requestFocus();
                JOptionPane.showMessageDialog(null, "repita sua senha","aviso",JOptionPane.WARNING_MESSAGE );
                return;
                }

        try {
            JOptionPane.showMessageDialog(null, "Seus dados estão cadastrados !","aviso",JOptionPane.WARNING_MESSAGE );
        } catch (HeadlessException e) {
        }
    
    
    
        
    }//GEN-LAST:event_cadastrar_PF_CADActionPerformed

    private void limpar_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_PF_CADActionPerformed
            nome_PF_CAD.setText("");
            rg_PF_CAD.setText("");
            cpf_PF_CAD.setText("");
            telefone_1_PF_CAD.setText("");
            telefone_2_PF_CAD.setText("");
            celular_PF_CAD.setText("");
            email_PF_CAD.setText("");
            conf_email_PF_CAD.setText("");
            senha_PF_CAD.setText("");
            conf_senha_PF_CAD.setText("");
            cep_PF_CAD.setText("");
            rua_PF_CAD.setText("");
            bairro_PF_CAD.setText("");
            cidade_PF_CAD.setText("");
            
            
            

    }//GEN-LAST:event_limpar_PF_CADActionPerformed

    private void telefone_1_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_1_PF_CADActionPerformed

    }//GEN-LAST:event_telefone_1_PF_CADActionPerformed

    private void celular_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celular_PF_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celular_PF_CADActionPerformed

    private void cpf_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_PF_CADActionPerformed

    }//GEN-LAST:event_cpf_PF_CADActionPerformed

    private void cep_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_PF_CADActionPerformed
        
    }//GEN-LAST:event_cep_PF_CADActionPerformed

    private void nome_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_PF_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_PF_CADActionPerformed

    private void sair_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_PF_CADActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_PF_CADActionPerformed

    private void tratamento_PF_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamento_PF_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamento_PF_CADActionPerformed

    private void cadastrar_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrar_PJ_CADActionPerformed

    private void limpar_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpar_PJ_CADActionPerformed

    private void sair_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sair_PJ_CADActionPerformed

    private void cpf_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_PJ_CADActionPerformed

    private void nome_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_PJ_CADActionPerformed

    private void cep_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_PJ_CADActionPerformed

    private void telefone_1_PJ_CADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_1_PJ_CADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_1_PJ_CADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JLabel Bairro1;
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel CEP1;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel CPF1;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel Cidade1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Estado1;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel RG;
    private javax.swing.JLabel RG1;
    private javax.swing.JLabel Rua;
    private javax.swing.JLabel Rua1;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Senha1;
    private javax.swing.JLabel Telefone_1;
    private javax.swing.JLabel Telefone_2;
    private javax.swing.JLabel Telefone_3;
    private javax.swing.JLabel Telefone_4;
    private javax.swing.JLabel Telefone_5;
    private javax.swing.JComboBox ano_nascimento_PF_CAD;
    private javax.swing.JTextField bairro_PF_CAD;
    private javax.swing.JTextField bairro_PJ_CAD;
    private javax.swing.JButton cadastrar_PF_CAD;
    private javax.swing.JButton cadastrar_PJ_CAD;
    private javax.swing.JTextArea campo_PF_CAD;
    private javax.swing.JFormattedTextField celular_PF_CAD;
    private javax.swing.JFormattedTextField cep_PF_CAD;
    private javax.swing.JFormattedTextField cep_PJ_CAD;
    private javax.swing.JTextField cidade_PF_CAD;
    private javax.swing.JTextField cidade_PJ_CAD;
    private javax.swing.JFormattedTextField cnpj_PJ_CAD;
    private javax.swing.JLabel conf_Email;
    private javax.swing.JLabel conf_Email1;
    private javax.swing.JLabel conf_Senha;
    private javax.swing.JLabel conf_Senha1;
    private javax.swing.JTextField conf_email_PF_CAD;
    private javax.swing.JTextField conf_email_PJ_CAD;
    private javax.swing.JTextField conf_senha_PF_CAD;
    private javax.swing.JTextField conf_senha_PJ_CAD;
    private javax.swing.JFormattedTextField cpf_PF_CAD;
    private javax.swing.JFormattedTextField cpf_PJ_CAD;
    private javax.swing.JComboBox dia_nascimento_PF_CAD;
    private javax.swing.JTextField email_PF_CAD;
    private javax.swing.JTextField email_PJ_CAD;
    private javax.swing.JComboBox estado_PF_CAD;
    private javax.swing.JComboBox estado_PJ_CAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton limpar_PF_CAD;
    private javax.swing.JButton limpar_PJ_CAD;
    private javax.swing.JComboBox mes_nascimento_PF_CAD;
    private javax.swing.JTextField nome_PF_CAD;
    private javax.swing.JTextField nome_PJ_CAD;
    private javax.swing.JSpinner numero_PF_CAD;
    private javax.swing.JSpinner numero_PJ_CAD;
    private javax.swing.JFormattedTextField rg_PF_CAD;
    private javax.swing.JTextField rua_PF_CAD;
    private javax.swing.JTextField rua_PJ_CAD;
    private javax.swing.JButton sair_PF_CAD;
    private javax.swing.JButton sair_PJ_CAD;
    private javax.swing.JTextField senha_PF_CAD;
    private javax.swing.JTextField senha_PJ_CAD;
    private javax.swing.JFormattedTextField telefone_1_PF_CAD;
    private javax.swing.JFormattedTextField telefone_1_PJ_CAD;
    private javax.swing.JFormattedTextField telefone_2_PF_CAD;
    private javax.swing.JFormattedTextField telefone_2_PJ_CAD;
    private javax.swing.JFormattedTextField telefone_3_PJ_CAD;
    private javax.swing.JTextArea texto_PJ_CAD;
    private javax.swing.JComboBox tratamento_PF_CAD;
    private javax.swing.JComboBox tratamento_PJ_CAD;
    // End of variables declaration//GEN-END:variables
}