package tcc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*; 

/**
 *
 * @author Higor
 */
public class Paginainicial extends javax.swing.JFrame {

    /**
     * Creates new form paginainicial
     */
    public Paginainicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadastrar_usuarios_PI = new javax.swing.JButton();
        consultar_PJ_PI = new javax.swing.JButton();
        sair_PI = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastrar_produtos_PI = new javax.swing.JButton();
        consultar_PF_PI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tcc/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("paginainicial.jLabel1.text_1")); // NOI18N

        cadastrar_usuarios_PI.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cadastrar_usuarios_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        cadastrar_usuarios_PI.setText(bundle.getString("paginainicial.jButton2.text_1")); // NOI18N
        cadastrar_usuarios_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_usuarios_PIActionPerformed(evt);
            }
        });

        consultar_PJ_PI.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        consultar_PJ_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lampada.png"))); // NOI18N
        consultar_PJ_PI.setText(bundle.getString("paginainicial.jButton3.text_1")); // NOI18N
        consultar_PJ_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_PJ_PIActionPerformed(evt);
            }
        });

        sair_PI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sair_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        sair_PI.setText(bundle.getString("Paginainicial_1.sair.text")); // NOI18N
        sair_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_PIActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel7.setText(bundle.getString("Paginainicial_1.jLabel7.text")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadeado_aberto.png"))); // NOI18N
        jLabel2.setText(bundle.getString("Paginainicial_1.jLabel2.text")); // NOI18N

        cadastrar_produtos_PI.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cadastrar_produtos_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        cadastrar_produtos_PI.setText(bundle.getString("Paginainicial_1.cadastrar_produtos.text")); // NOI18N
        cadastrar_produtos_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_produtos_PIActionPerformed(evt);
            }
        });

        consultar_PF_PI.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        consultar_PF_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lampada.png"))); // NOI18N
        consultar_PF_PI.setText(bundle.getString("Paginainicial_1.consultar_PF.text")); // NOI18N
        consultar_PF_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_PF_PIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sair_PI))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(244, 244, 244)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(consultar_PF_PI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastrar_produtos_PI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastrar_usuarios_PI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consultar_PJ_PI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(consultar_PF_PI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultar_PJ_PI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar_usuarios_PI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar_produtos_PI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair_PI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_PJ_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_PJ_PIActionPerformed
            new ConsultaClientePJ().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_consultar_PJ_PIActionPerformed

    private void sair_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_PIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_PIActionPerformed

    private void consultar_PF_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_PF_PIActionPerformed
            new ConsultaClientePF().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_consultar_PF_PIActionPerformed

    private void cadastrar_usuarios_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_usuarios_PIActionPerformed
            new Cadastrar().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_cadastrar_usuarios_PIActionPerformed

    private void cadastrar_produtos_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_produtos_PIActionPerformed
            new CadastrarProdutos().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_cadastrar_produtos_PIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paginainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paginainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paginainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paginainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Paginainicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_produtos_PI;
    private javax.swing.JButton cadastrar_usuarios_PI;
    private javax.swing.JButton consultar_PF_PI;
    private javax.swing.JButton consultar_PJ_PI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton sair_PI;
    // End of variables declaration//GEN-END:variables
}
